version: "3.8"

services:
  dummy:
    platform: linux/amd64
    build:
      context: lambdas/dummy
    volumes:
      - ./lambdas/dummy/src/coverage:/app/src/coverage

  rummy:
    platform: linux/amd64
    build:
      context: lambdas/rummy
    volumes:
      - ./lambdas/rummy/src/coverage:/app/src/coverage
