version: "3.8"

services:
  dummy:
    platform: linux/amd64
    build:
      context: lambdas/dummy
    volumes:
      - ./coverage:/coverage
      - ./lambdas/dummy/src/coverage:/app/src/coverage

secrets:
  codeartifact-auth-token:
    file: .codeartifact_token