version: 2.1

orbs:
  python: circleci/python@2.1.1
            

jobs:
  build:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true

    steps:
      - checkout
      - run:
          name: "Setup Code Climate test-reporter"
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
      - run:
          name: "Create coverage folder"
          command: mkdir coverage
      - run:
          name: "Install lambda deps"
          command: make install-deps
      - persist_to_workspace:
          root: .
          paths:
            - .

  upload-coverage-codeclimate:
    docker:
      - image: cimg/python:3.8-node

    steps:
      - attach_workspace:
          at: .
      - run:
          name: "list files"
          command: ls coverage/
      - run:
          name: "x"
          command: cat coverage/coverage.dummy.json
      - run:
          name: "y"
          command: cat coverage/coverage.rummy.json
      - run:
          name: "z"
          command: cat coverage/coverage.stack.json
      - run:
          name: "Combine coverage results"
          command: |
            ./cc-test-reporter sum-coverage coverage/coverage.*.json -p 3 -o coverage/codeclimate.combined.json
      - run:
          name: "w"
          command: cat coverage/codeclimate.combined.json
      - run:
          name: "Upload coverage results to Code Climate"
          command: |
            ./cc-test-reporter upload-coverage -i coverage/codeclimate.combined.json -d

  unit-tests-dummy:
    machine:
      image: ubuntu-2204:current

    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Run tests for dummy"
          command: make test-dummy
      - run:
          name: "Run format-coverage"
          command: |
            cd lambdas/dummy/src
            $CIRCLE_WORKING_DIRECTORY/cc-test-reporter format-coverage -t coverage.py coverage/coverage.dummy.xml -d -o $CIRCLE_WORKING_DIRECTORY/coverage/coverage.dummy.json
      - persist_to_workspace:
          root: .
          paths:
            - coverage

  unit-tests-rummy:
    machine:
      image: ubuntu-2204:current

    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Run tests for rummy"
          command: make test-rummy
      - run:
          name: "Run format-coverage"
          command: |
            cd lambdas/rummy/src
            $CIRCLE_WORKING_DIRECTORY/cc-test-reporter format-coverage -t coverage.py coverage/coverage.rummy.xml -d -o $CIRCLE_WORKING_DIRECTORY/coverage/coverage.rummy.json
      - persist_to_workspace:
          root: .
          paths:
            - coverage

  unit-tests-stack:
    machine:
      image: ubuntu-2204:current

    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Install stack deps for tests"
          command: pip3 install -r requirements-dev.txt
      - run:
          name: "Run tests"
          command: make test-stack
      - run:
          name: "Run format-coverage"
          command: |
            cd stack
            $CIRCLE_WORKING_DIRECTORY/cc-test-reporter format-coverage -t coverage.py coverage/coverage.stack.xml -d -o $CIRCLE_WORKING_DIRECTORY/coverage/coverage.stack.json
      - persist_to_workspace:
          root: .
          paths:
            - coverage

workflows:
  version: 2

  pull-request:
    jobs:
      - build:
          context:
            - "Prod AWS"
      - unit-tests-rummy:
          requires:
            - build
      - unit-tests-dummy:
          requires:
            - build
      - unit-tests-stack:
          requires:
            - build
      - upload-coverage-codeclimate:
          requires:
            - unit-tests-rummy
            - unit-tests-dummy
            - unit-tests-stack
